### ISSUE TITLE
Messy state transitions

### ISSUE THREAD

**Issue by janm399** [muvr/muvr-pebble#10]
The transitions in the flow

``not exercising - (tap) -> exercising - (tap) -> classified -> not exercising - (tap) -> exercising``

are not working reliably. Reproduce the problem and fix.

**Comment by tmbo** [comment]
I actually found the reason why the pebble is showing the 'not moving' symbol. It is because the fuser in the pre-classification package decides that the pebble is not moving and sets the `fusionResult.type()` to `sensor_data_fuser::fusion_result::not_moving`. The ios app will send a notification to the pebble (`0xa0000000`) which results in a call to `rx_not_moving` on the pebble.

I am not sure what the best way would be to fix it, but there are several. One way would be to change `MRMode.reportMovementExercise` to `true` for the assisted classification mode. 

@janm399 do you now why the condition in this line https://github.com/muvr/muvr-ios/blob/develop/Muvr/MRExerciseSessionViewController.swift#L266 is negated for `notMoving` but it isn't for the other two `moving` and `exercising`? We could just remove the negation...

**Comment by janm399** [comment]
Line 266 looks like another bug. Though ``reportMovementExercise`` is always ``false`` in ``.AssistedClassification``, so the delegate implementations in ``MRExerciseSessionViewController`` should not run:

```swift
    ...

    func moving() {
        if waitingForUser { return }
        if let x: MRExerciseBlockDelegate = currentPageViewController() { x.moving() }
        if mode!.reportMovementExercise /* == false */ {  pcd.notifyMoving() }
    }

    ...
```

**Comment by tmbo** [comment]
That is right and exactly what I mean. Because of `if !mode!.reportMovementExercise` in L266 the delegate will get called for the `notMoving` function. So we should probably just remove the `!`

**Comment by janm399** [comment]
I see. Yes.
